name: rentease
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  sqflite_common_ffi: ^2.2.0
  sqflite: ^2.2.8+4
  path: ^1.8.3
  image_picker: ^0.8.9

  google_fonts: ^4.0.4

  # Gestion d'√©tat et navigation facile avec GetX
  get: ^4.6.5

  # Stockage local pour savoir si l'onboarding a d√©j√† √©t√© vu
  shared_preferences: ^2.1.1

  # Gestion des Assets et des images
  flutter_svg: ^2.0.7  # si tu utilises des SVG pour tes images
  provider: ^6.0.0
  path_provider: ^2.0.0
  crypto: ^3.0.0
  flutter_native_splash: ^2.3.2
  smooth_page_indicator: ^1.1.0

  mailer: ^6.0.0

  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^7.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - Assets/
    - Assets/images/

# üëá Cette section configure ton splash screen !
flutter_native_splash:
  color: "#FFFFFF"          # Couleur d‚Äôarri√®re-plan claire
  color_dark: "#272727"     # Couleur d‚Äôarri√®re-plan sombre
  image: Assets/logos/logo.png   # Ton logo affich√© au lancement

  android_12:
    color: "#FFFFFF"
    color_dark: "#272727"
    image: Assets/logos/logo.png

  web: false
